openapi: 3.0.2
info:
  version: v1.0
  title: S-Coin Blockchain API
  description: Rest API for interacting with the S-Coin blockchain
  contact:
    name: Sadat Malik
    url: http://creativefusion.net
    email: sadat.malik@me.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Self node
  - url: http://localhost:8081
    description: Badger node
  - url: http://localhost:8082
    description: Pal node
paths:
  /v1/mine-block:
    get:
      responses:
        '200':
          description: Newly inserted block
          content:
            application/json:
              schema:
                type: object
                properties:
                  index:
                    type: integer
                    example: 6
                  timeStamp:
                    type: string
                    example: 22-04-2022 14:30:31
                  proof:
                    type: integer
                    example: 104205
                  previousHash:
                    type: string
                    example: 3c938755101a7b975808daf0b5c174f8c745a55497bd09732e6b19c5f313272e
                  transactions:
                    type: object
                    properties:
                      sender:
                        type: string
                        example: 2c320ba9dcec48a28b123d84ea819488
                      receiver:
                        type: string
                        example: sadat
                      amount:
                        type: integer
                        example: 1