openapi: 3.0.2
info:
  version: v1.0
  title: S-Coin Blockchain API
  description: Rest API for interacting with the S-Coin blockchain
  contact:
    name: Sadat Malik
    url: http://creativefusion.net
    email: sadat.malik@me.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Self node
  - url: http://localhost:8081
    description: Badger node
  - url: http://localhost:8082
    description: Pal node

paths:
  /v1/mine-block:
    get:
      summary: Mine a new block.
      description: Mines a new block containing the required proof of work. Includes a single transaction representing the mined coin value issued to the miner.
      responses:
        '200':
          description: New block
          content:
            application/json:
              schema:
                type: object
                properties:
                  index:
                    type: integer
                    example: 6
                  timeStamp:
                    type: string
                    example: 22-04-2022 14:30:31
                  proof:
                    type: integer
                    example: 104205
                  previousHash:
                    type: string
                    example: 3c938755101a7b975808daf0b5c174f8c745a55497bd09732e6b19c5f313272e
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        sender:
                          type: string
                          example: 2c320ba9dcec48a28b123d84ea819488
                        receiver:
                          type: string
                          example: sadat
                        amount:
                          type: integer
                          example: 1
  /v1/get-chain:
    get:
      summary: Requests the full blockchain.
      description: Constructs and returns a data transfer object containing the full list of blocks in the blockchain and the current chain size.
      responses:
        '200':
          description: The block chain
          content:
            application/json:
              schema:
                type: object
                properties:
                  chain:
                    type: array
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          example: 2
                        timeStamp:
                          type: string
                          example: 24-04-2022 15:21:41
                        proof:
                          type: integer
                          example: 38561
                        previousHash:
                          type: string
                          example: b7f1f36decd1fcc72095e3912c20111ffc57634bfb5a959782244fbec12c07a0
                        transactions:
                          type: array
                          items:
                            type: object
                            properties:
                              sender:
                                type: string
                                example: 2c320ba9dcec48a28b123d84ea819488
                              receiver:
                                type: string
                                example: sadat
                              amount:
                                type: integer
                                example: 1
                  size:
                    type: integer
                    example: 1




